#!/usr/bin/env bash
# =============================================================================
# pc7-certificate-authority.sh
# Installation and Configuration of a Certificate Authority (CA)
# SRE Cryptography Guide - Practical Case 7
# =============================================================================
# Description:
#   Creates a self-signed Root Certificate Authority using OpenSSL.
#   Establishes the directory structure, generates the CA private key,
#   and self-signs the CA certificate.
#   This is the Linux/OpenSSL equivalent of the Windows IIS CA from the textbook.
# Prerequisites:
#   - openssl installed
#   - bash
# Usage:
#   bash pc7-certificate-authority.sh [ca_name] [ca_dir]
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------
CA_NAME="${1:-SiTourCA}"
CA_DIR="${2:-/tmp/ca-${CA_NAME}}"
CA_COUNTRY="ES"
CA_STATE="Segovia"
CA_LOCALITY="Fuentemilanos"
CA_ORG="SITOUR SA"
CA_OU="Division de certificados"
CA_EMAIL="macarena@sitour.com"
CA_DAYS=3650  # 10 years for root CA
CA_KEY_BITS=4096
CA_SUBJECT="/C=${CA_COUNTRY}/ST=${CA_STATE}/L=${CA_LOCALITY}/O=${CA_ORG}/OU=${CA_OU}/CN=${CA_NAME}/emailAddress=${CA_EMAIL}"

echo "============================================================"
echo " PC7 - Certificate Authority Installation"
echo " SRE Cryptography Automation Guide"
echo "============================================================"
echo ""

# ---------------------------------------------------------
# Step 1: Check prerequisites
# ---------------------------------------------------------
echo "[STEP 1] Checking prerequisites..."

if ! command -v openssl &>/dev/null; then
    echo "[ERROR] openssl not found."
    echo "        Install with: nix-shell -p openssl"
    exit 1
fi

echo "[OK]    OpenSSL version: $(openssl version)"
echo ""

# ---------------------------------------------------------
# Step 2: Create CA directory structure
# ---------------------------------------------------------
echo "[STEP 2] Creating CA directory structure at: ${CA_DIR}"

mkdir -p "${CA_DIR}"/{certs,crl,newcerts,private,requests}
chmod 700 "${CA_DIR}/private"
touch "${CA_DIR}/index.txt"
echo "1000" > "${CA_DIR}/serial"
echo "1000" > "${CA_DIR}/crlnumber"

echo "[OK]    Directory structure created."
echo "        ${CA_DIR}/"
echo "        ├── certs/       (issued certificates)"
echo "        ├── crl/         (certificate revocation lists)"
echo "        ├── newcerts/    (copies of issued certs)"
echo "        ├── private/     (CA private key - mode 700)"
echo "        ├── requests/    (pending CSRs)"
echo "        ├── index.txt    (certificate database)"
echo "        └── serial       (certificate serial counter)"
echo ""

# ---------------------------------------------------------
# Step 3: Create OpenSSL configuration file
# ---------------------------------------------------------
CA_CONF="${CA_DIR}/openssl.cnf"
echo "[STEP 3] Creating OpenSSL configuration: ${CA_CONF}"

cat > "${CA_CONF}" <<EOF
# OpenSSL CA Configuration - ${CA_NAME}
# Generated by pc7-certificate-authority.sh

[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = ${CA_DIR}
certs             = \$dir/certs
crl_dir           = \$dir/crl
new_certs_dir     = \$dir/newcerts
database          = \$dir/index.txt
serial            = \$dir/serial
RANDFILE          = \$dir/private/.rand
private_key       = \$dir/private/ca.key.pem
certificate       = \$dir/certs/ca.cert.pem
crlnumber         = \$dir/crlnumber
crl               = \$dir/crl/ca.crl.pem
crl_extensions    = crl_ext
default_crl_days  = 30
default_md        = sha256
name_opt          = ca_default
cert_opt          = ca_default
default_days      = 375
preserve          = no
policy            = policy_strict
copy_extensions   = copy

[ policy_strict ]
countryName             = match
stateOrProvinceName     = match
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ policy_loose ]
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ req ]
default_bits        = 4096
distinguished_name  = req_distinguished_name
string_mask         = utf8only
default_md          = sha256
x509_extensions     = v3_ca
prompt              = no

[ req_distinguished_name ]
C  = ${CA_COUNTRY}
ST = ${CA_STATE}
L  = ${CA_LOCALITY}
O  = ${CA_ORG}
OU = ${CA_OU}
CN = ${CA_NAME}
emailAddress = ${CA_EMAIL}

[ v3_ca ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical, CA:true
keyUsage               = critical, digitalSignature, cRLSign, keyCertSign

[ v3_intermediate_ca ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical, CA:true, pathlen:0
keyUsage               = critical, digitalSignature, cRLSign, keyCertSign

[ usr_cert ]
basicConstraints       = CA:FALSE
nsCertType             = client, email
nsComment              = "OpenSSL Generated Client Certificate"
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer
keyUsage               = critical, nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage       = clientAuth, emailProtection

[ server_cert ]
basicConstraints       = CA:FALSE
nsCertType             = server
nsComment              = "OpenSSL Generated Server Certificate"
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer:always
keyUsage               = critical, digitalSignature, keyEncipherment
extendedKeyUsage       = serverAuth

[ crl_ext ]
authorityKeyIdentifier = keyid:always

[ ocsp ]
basicConstraints       = CA:FALSE
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer
keyUsage               = critical, digitalSignature
extendedKeyUsage       = critical, OCSPSigning
EOF

echo "[OK]    Configuration file created."
echo ""

# ---------------------------------------------------------
# Step 4: Generate CA private key
# ---------------------------------------------------------
CA_KEY="${CA_DIR}/private/ca.key.pem"
echo "[STEP 4] Generating CA private key (RSA ${CA_KEY_BITS}-bit): ${CA_KEY}"

openssl genrsa \
    -out "${CA_KEY}" \
    "${CA_KEY_BITS}"

chmod 400 "${CA_KEY}"
echo "[OK]    CA private key created (permissions: 400)."
echo ""

# ---------------------------------------------------------
# Step 5: Generate self-signed CA certificate
# ---------------------------------------------------------
CA_CERT="${CA_DIR}/certs/ca.cert.pem"
echo "[STEP 5] Generating self-signed CA certificate (valid ${CA_DAYS} days)..."
echo "[INFO]   Subject: ${CA_SUBJECT}"

openssl req \
    -config "${CA_CONF}" \
    -key "${CA_KEY}" \
    -new \
    -x509 \
    -days "${CA_DAYS}" \
    -sha256 \
    -extensions v3_ca \
    -subj "${CA_SUBJECT}" \
    -out "${CA_CERT}"

chmod 444 "${CA_CERT}"
echo "[OK]    CA certificate created (permissions: 444)."
echo ""

# ---------------------------------------------------------
# Step 6: Verify the CA certificate
# ---------------------------------------------------------
echo "[STEP 6] Verifying CA certificate..."
echo ""
openssl x509 -noout -text -in "${CA_CERT}" | grep -E "(Subject:|Issuer:|Not Before|Not After|Public-Key:|CA:)"
echo ""

echo "[OK]    CA self-verification:"
openssl verify -CAfile "${CA_CERT}" "${CA_CERT}" 2>&1 || echo "[INFO] Self-signed cert; verify against itself is expected behavior."
echo ""

# ---------------------------------------------------------
# Step 7: Generate initial CRL
# ---------------------------------------------------------
echo "[STEP 7] Generating initial Certificate Revocation List (CRL)..."

openssl ca \
    -config "${CA_CONF}" \
    -gencrl \
    -out "${CA_DIR}/crl/ca.crl.pem" 2>/dev/null

echo "[OK]    Initial CRL created: ${CA_DIR}/crl/ca.crl.pem"
echo ""

# ---------------------------------------------------------
# Summary
# ---------------------------------------------------------
echo "[SUMMARY]"
echo "  CA Name        : ${CA_NAME}"
echo "  CA Directory   : ${CA_DIR}"
echo "  CA Private Key : ${CA_KEY}"
echo "  CA Certificate : ${CA_CERT}"
echo "  CA Config      : ${CA_CONF}"
echo "  CA CRL         : ${CA_DIR}/crl/ca.crl.pem"
echo "  Validity       : ${CA_DAYS} days"
echo "  Key Size       : ${CA_KEY_BITS} bits"
echo ""
echo "[NEXT STEPS]"
echo "  1. Issue certificates: bash pc8-certificate-request.sh"
echo "  2. Distribute CA cert to clients: ${CA_CERT}"
echo "  3. Publish CRL to accessible location"
echo ""
echo "[SRE NOTE]"
echo "  In production, the CA private key must be stored on an"
echo "  HSM (Hardware Security Module) or offline vault."
echo "  The CA certificate should be distributed via a trusted channel."
echo "============================================================"